const routes = require('next-routes')

module.exports = routes()
  // page routes
  // main routes
  .add('/', 'Screen/HomeScreen')
  .add('/my-nfts', 'Screen/MyNFTScreen')
  .add('/infor-user', 'Screen/InforUserScreen')
  .add('/infor-user/:id', 'Screen/InforUserScreen')
  .add('/ranking-users', 'Screen/RankingUserScreen')
  .add('/ranking-users/:id', 'Screen/RankingUserScreen')
  .add('my-nfts-detail', '/my-nfts/:nftAddress/:id', 'Screen/MyNFTScreen/Subview/MyNFTDetailMobile')
  .add('/my-nfts/sell/:nftAddress/:nftId', 'Screen/MyNFTScreen/Components/SellNFT')
  .add('/nft/change-price/:nftAddress/:nftId', 'Screen/MyNFTScreen/Components/ChangePriceNFT')
  .add('/marketplace', 'Screen/Marketplace')
  .add('/marketplace/spheres', 'Screen/Marketplace/Spheres')
  .add('/marketplace/items', 'Screen/Marketplace/Items')
  .add('/marketplace/characters', 'Screen/Marketplace/Characters')
  .add('/marketplace/:nftAddress/:nftId', 'Screen/Marketplace/Components/NftDetails')
  .add('/marketplace/:type/:nftAddress/:nftId', 'Screen/Marketplace/Components/NftDetails')
  .add('nft-detail', '/nft/:nftAddress/:nftId', 'Screen/NFTDetailScreen')
  .add('/nft-card', 'Screen/HowToUseScreen')
  .add('/nft-card/:id', 'Screen/HowToUseScreen')
  .add('/my-nft-detail', 'Screen/MyNFTDetailScreen')
  .add('/my-nft-detail/:nftAddress/:id', 'Screen/MyNFTDetailScreen')
  .add('/my-asset-detail/character/:id', 'Screen/MyIngameAssetDetails')
  .add('/my-asset-detail/item/:id', 'Screen/MyIngameAssetDetails')
  .add('/receive-link', 'Screen/HowToUseScreen')
  .add('/receive-link/:id', 'Screen/HowToUseScreen')
  .add('/campaign', 'Screen/HowToUseScreen')
  .add('/campaign', 'Screen/HowToUseScreen')
  .add('/campaign/:id', 'Screen/HowToUseScreen')
  .add('/campaign/nftgame/:id', 'Screen/HowToUseScreen')
  .add('/board-game-1', 'Screen/BoardGame')
  .add('/store-game', 'Screen/StoreGame')
  .add('/nft-market', 'Screen/NFTMarket')
  .add('/ranking', 'Screen/UserRankingScreen')
  .add('/playGame', 'Screen/PlayGameScreen')
  .add('/buyToken', 'Screen/BuyTokenScreen')
  .add('/error', 'pages/_error')
  .add('/gacha', 'Screen/Gacha')
  .add('/store', 'Screen/NftStore')
  .add('/store/nft/:id', 'Screen/NftStore/Components/NftDetails')
  .add('/user/:address', 'Screen/UserDetails')
  .add('/receive-characters', 'Screen/GameScreen')
  .add('/scholarship', 'Screen/ScholarshipScreen')
  .add('/nft-detail-scholarship/:nftAddress/:id', 'Screen/NFTDetailScholarshipScreen')
  .add('/nft-detail-scholarship/:nftAddress/:id', 'Screen/NFTDetailScholarshipScreen')
  .add('/game-bounty-belt', 'Screen/GameBountyBelt')
